export const GET_USERS_PENDING = "GET_USERS_PENDING";
export const GET_USERS = " GET_USERS";
export const GET_USERS_FAIL = "GET_USERS_FAIL";

export const GET_SUBSCRIPTION_PENDING = "GET_SUBSCRIPTION_PENDING";
export const GET_SUBSCRIPTION = "GET_SUBSCRIPTION";
export const GET_SUBSCRIPTION_FAIL = "GET_SUBSCRIPTION_FAIL";

export const GET_PAID_SUBSCRIPTION_PENDING = "GET_PAID_SUBSCRIPTION_PENDING";
export const GET_PAID_SUBSCRIPTION = "GET_PAID_SUBSCRIPTION";
export const GET_PAID_SUBSCRIPTION_FAIL = "GET_PAID_SUBSCRIPTION_FAIL";

export const GET_USER_LIST_PENDING = "GET_USER_LIST_PENDING";
export const GET_USER_LIST = "GET_USER_LIST";
export const GET_USER_LIST_FAIL = "GET_USER_LIST_FAIL";

export const PUT_COMPANYLIST_PENDING = "PUT_COMPANYLIST_PENDING";
export const PUT_COMPANYLIST_SUCCESS = "PUT_COMPANYLIST_SUCCESS";
export const PUT_COMPANYLIST_FAIL = "PUT_COMPANYLIST_FAIL";

export const PUT_ADDUSERBTN_PENDING = "PUT_ADDUSERBTN_PENDING";
export const PUT_ADDUSERBTN_SUCCESS = "PUT_ADDUSERBTN_SUCCESS";
export const PUT_ADDUSERBTN_FAIL = "PUT_ADDUSERBTN_FAIL";


export const PUT_USERMANAGMENT_PENDING = "PUT_USERMANAGMENT_PENDING";
export const PUT_USERMANAGMENT_SUCCESS = "PUT_USERMANAGMENT_SUCCESS";
export const PUT_USERMANAGMENT_FAIL = "PUT_USERMANAGMENT_FAIL";


export const GET_EXTRAPAGE_PENDING = "GET_EXTRAPAGE_PENDING";
export const GET_EXTRAPAGE_SUCCESS = "GET_EXTRAPAGE_SUCCESS";
export const GET_EXTRAPAGE_FAIL = "GET_EXTRAPAGE_FAIL"; 