export const GET_USERS_PENDING = "GET_USERS_PENDING";
export const GET_USERS = " GET_USERS";
export const GET_USERS_FAIL = "GET_USERS_FAIL";

export const GET_SUBSCRIPTION_PENDING = "GET_SUBSCRIPTION_PENDING";
export const GET_SUBSCRIPTION = "GET_SUBSCRIPTION";
export const GET_SUBSCRIPTION_FAIL = "GET_SUBSCRIPTION_FAIL";

export const GET_PAID_SUBSCRIPTION_PENDING = "GET_PAID_SUBSCRIPTION_PENDING";
export const GET_PAID_SUBSCRIPTION = "GET_PAID_SUBSCRIPTION";
export const GET_PAID_SUBSCRIPTION_FAIL = " GET_PAID_SUBSCRIPTION_FAIL";

export const GET_USER_LIST_PENDING = "GET_USER_LIST_PENDING";
export const GET_USER_LIST = "GET_USER_LIST";
export const GET_USER_LIST_FAIL = "GET_USER_LIST_FAIL";

export const PUT_COMPANYLIST_PENDING = "PUT_COMPANYLIST_PENDING";
export const PUT_COMPANYLIST_SUCCESS = "PUT_COMPANYLIST_SUCCESS";
export const PUT_COMPANYLIST_FAIL = "PUT_COMPANYLIST_FAIL";

export const PUT_ADDUSERBTN_PENDING = "PUT_ADDUSERBTN_PENDING";
export const PUT_ADDUSERBTN_SUCCESS = "PUT_ADDUSERBTN_SUCCESS";
export const PUT_ADDUSERBTN_FAIL = "PUT_ADDUSERBTN_FAIL";

export const PUT_USERMANAGMENT_PENDING = "PUT_USERMANAGMENT_PENDING";
export const PUT_USERMANAGMENT_SUCCESS = "PUT_USERMANAGMENT_SUCCESS";
export const PUT_USERMANAGMENT_FAIL = "PUT_USERMANAGMENT_FAIL";

export const GET_EXTRAPAGE_PENDING = "GET_EXTRAPAGE_PENDING";
export const GET_EXTRAPAGE_SUCCESS = "GET_EXTRAPAGE_SUCCESS";
export const GET_EXTRAPAGE_FAIL = "GET_EXTRAPAGE_FAIL";

export const GET_USERS_ADD_PENDING = "GET_USERS_ADD_PENDING";
export const GET_ADD_USERS = " GET_ADD_USERS";
export const GET_USERS_ADD_FAIL = "GET_USERS_ADD_FAIL";

export const GET_USERS_APPROVE_PENDING = "GET_USERS_APPROVE_PENDING";
export const GET_APPROVE_USERS = " GET_APPROVE_USERS";
export const GET_USERS_APPROVE_FAIL = "GET_USERS_APPROVE_FAIL";

export const GET_USERS_DENY_PENDING = "GET_USERS_DENY_PENDING";
export const GET_DENY_USERS = " GET_DENY_USERS";
export const GET_USERS_DENY_FAIL = " GET_USERS_DENY_FAIL";

export const GET_COMPANY_DETAIL_ADD_PENDING = "GET_COMPANY_DETAIL_ADD_PENDING";
export const GET_COMPANY_DETAIL_ADD = " GET_COMPANY_DETAIL_ADD";
export const GET_COMPANY_DETAIL_ADD_FAIL = " GET_COMPANY_DETAIL_ADD_FAIL";

export const GET_ALL_USER_DATA_PENDING = "GET_ALL_USER_DATA_PENDING";
export const GET_ALL_USER_DATA_SUCCESS = "GET_ALL_USER_DATA_SUCCESS";
export const GET_ALL_USER_DATA_FAILED = "GET_ALL_USER_DATA_FAILED";


export const GET_USER_DATA_REMOVE_PENDING = "GET_USER_DATA_REMOVE_PENDING";
export const GET_USER_DATA_REMOVE_SUCCESS = "GET_USER_DATA_REMOVE_SUCCESS";
export const GET_USER_DATA_REMOVE_FAILED = "GET_USER_DATA_REMOVE_FAILED";

export const GET_USER_DATA_EDIT_PENDING = "GET_USER_DATA_EDIT_PENDING";
export const GET_USER_DATA_EDIT_SUCCESS = "GET_USER_DATA_EDIT_SUCCESS";
export const GET_USER_DATA_EDIT_FAILED = "GET_USER_DATA_EDIT_FAILED";